# roles.py
# ВНИМАНИЕ: позиции (1-5) эвристические, зависят от меты. Правь вручную под актуальный патч.
# Формат: ID: ["English Name", "Русское имя / сленг", [позиции]]

HERO_DB = {
    1: ["Anti-Mage", "Анти-Маг", [1]],
    2: ["Axe", "Акс", [3]],
    3: ["Bane", "Бейн", [4, 5]],
    4: ["Bloodseeker", "Бладсикер", [1, 2, 3]],
    5: ["Crystal Maiden", "Кристал Мейден", [4, 5]],
    6: ["Drow Ranger", "Дроу Рейнджер", [1]],
    7: ["Earthshaker", "Шейкер", [2, 3, 4]],
    8: ["Juggernaut", "Джаггернаут", [1]],
    9: ["Mirana", "Мирана", [2, 4, 5]],
    10: ["Morphling", "Морфлинг", [1, 2]],
    11: ["Shadow Fiend", "Шадоу Финд", [1, 2]],
    12: ["Phantom Lancer", "Фантом Лансер", [1]],
    13: ["Puck", "Пак", [2, 3]],
    14: ["Pudge", "Пудж", [2, 3, 4, 5]],
    15: ["Razor", "Разор", [1, 2, 3]],
    16: ["Sand King", "Сэнд Кинг", [2, 3, 4]],
    17: ["Storm Spirit", "Шторм Спирит", [2]],
    18: ["Sven", "Свен", [1, 3]],
    19: ["Tiny", "Тини", [1, 2, 3, 4]],
    20: ["Vengeful Spirit", "Венга", [1, 3, 4, 5]],
    21: ["Windranger", "ВинДрейнджер", [2, 3, 4]],
    22: ["Zeus", "Зевс", [2, 4]],
    23: ["Kunkka", "Кункка", [2, 3, 4]],
    25: ["Lina", "Лина", [1, 2, 4]],
    26: ["Lion", "Лион", [4, 5]],
    27: ["Shadow Shaman", "Раста", [4, 5]],
    28: ["Slardar", "Сладар", [1, 3]],
    29: ["Tidehunter", "Тайдхантер", [3]],
    30: ["Witch Doctor", "Витч Доктор", [4, 5]],
    31: ["Lich", "Лич", [4, 5]],
    32: ["Riki", "Рики", [1, 4]],
    33: ["Enigma", "Энигма", [3, 4]],
    34: ["Tinker", "Тинкер", [2]],
    35: ["Sniper", "Снайпер", [1, 2, 4]],
    36: ["Necrophos", "Некрофос", [1, 2, 3]],
    37: ["Warlock", "Варлок", [5]],
    38: ["Beastmaster", "Бистмастер", [3]],
    39: ["Queen of Pain", "Квопа", [2]],
    40: ["Venomancer", "Веномансер", [3, 4, 5]],
    41: ["Faceless Void", "Войд", [1]],
    42: ["Wraith King", "Врайт Кинг", [1, 3]],
    43: ["Death Prophet", "ДП", [2, 3]],
    44: ["Phantom Assassin", "Фантом Ассассин", [1]],
    45: ["Pugna", "Пугна", [2, 4, 5]],
    46: ["Templar Assassin", "Темпларка", [1, 2]],
    47: ["Viper", "Вайпер", [2, 3]],
    48: ["Luna", "Луна", [1]],
    49: ["Dragon Knight", "ДК", [1, 2, 3]],
    50: ["Dazzle", "Дазл", [2, 4, 5]],
    51: ["Clockwerk", "Клокверк", [3, 4, 5]],
    52: ["Leshrac", "Лешрак", [1, 2, 3]],
    53: ["Nature's Prophet", "Фурион", [1, 2, 3]],
    54: ["Lifestealer", "Лайфстилер", [1]],
    55: ["Dark Seer", "Дарк Сир", [3]],
    56: ["Clinkz", "Клинкз", [1, 2]],
    57: ["Omniknight", "Омник", [3, 4, 5]],
    58: ["Enchantress", "Энча", [3, 4, 5]],
    59: ["Huskar", "Хускар", [1, 2]],
    60: ["Night Stalker", "Найт Сталкер", [3]],
    61: ["Broodmother", "Бруда", [2, 3]],
    62: ["Bounty Hunter", "БХ", [3, 4]],
    63: ["Weaver", "Вивер", [1, 3, 4]],
    64: ["Jakiro", "Джакиро", [4, 5]],
    65: ["Batrider", "Батрайдер", [2, 3, 4]],
    66: ["Chen", "Чен", [4, 5]],
    67: ["Spectre", "Спектра", [1]],
    68: ["Ancient Apparition", "АА", [4, 5]],
    69: ["Doom", "Дум", [3]],
    70: ["Ursa", "Урса", [1]],
    71: ["Spirit Breaker", "Баратрум", [3, 4]],
    72: ["Gyrocopter", "Гирокоптер", [1, 2, 4]],
    73: ["Alchemist", "Алхимик", [1, 2]],
    74: ["Invoker", "Инвокер", [2]],
    75: ["Silencer", "Сайленсер", [2, 4, 5]],
    76: ["Outworld Destroyer", "ОД", [2]],
    77: ["Lycan", "Ликан", [1, 3]],
    78: ["Brewmaster", "Брюмастер", [3]],
    79: ["Shadow Demon", "ШД", [4, 5]],
    80: ["Lone Druid", "Лон Друид", [1, 2]],
    81: ["Chaos Knight", "ЦК", [1, 3]],
    82: ["Meepo", "Мипо", [1, 2]],
    83: ["Treant Protector", "Трент", [4, 5]],
    84: ["Ogre Magi", "Огр Маг", [3, 4, 5]],
    85: ["Undying", "Андайинг", [3, 4, 5]],
    86: ["Rubick", "Рубик", [2, 4]],
    87: ["Disruptor", "Дизраптор", [4, 5]],
    88: ["Nyx Assassin", "Никс", [4]],
    89: ["Naga Siren", "Нага Сирен", [1, 4]],
    90: ["Keeper of the Light", "Котл", [2, 4, 5]],
    91: ["Io", "Висп", [4, 5]],
    92: ["Visage", "Визаж", [2, 3, 4]],
    93: ["Slark", "Сларк", [1]],
    94: ["Medusa", "Медуза", [1, 2]],
    95: ["Troll Warlord", "Тролль", [1]],
    96: ["Centaur Warrunner", "Кентавр", [3]],
    97: ["Magnus", "Магнус", [2, 3]],
    98: ["Timbersaw", "Тимбер", [2, 3]],
    99: ["Bristleback", "Бристлбек", [1, 3]],
    100: ["Tusk", "Туск", [2, 3, 4]],
    101: ["Skywrath Mage", "Скай", [2, 4, 5]],
    102: ["Abaddon", "Аббадон", [1, 3, 4, 5]],
    103: ["Elder Titan", "Титан", [3, 4, 5]],
    104: ["Legion Commander", "Легионка", [1, 3]],
    105: ["Techies", "Течис", [4, 5]],
    106: ["Ember Spirit", "Эмбер", [1, 2]],
    107: ["Earth Spirit", "Земеля", [2, 4]],
    108: ["Underlord", "Андерлорд", [3]],
    109: ["Terrorblade", "Террорблейд", [1]],
    110: ["Phoenix", "Феникс", [3, 4, 5]],
    111: ["Oracle", "Оракл", [4, 5]],
    112: ["Winter Wyvern", "Виверна", [2, 4, 5]],
    113: ["Arc Warden", "Арк Варден", [1, 2]],
    114: ["Monkey King", "МК", [1, 2, 4]],
    119: ["Dark Willow", "Дарк Виллоу", [2, 4]],
    120: ["Pangolier", "Пангольер", [2, 3, 4]],
    121: ["Grimstroke", "Гримстрок", [4, 5]],
    123: ["Hoodwink", "Худвинк", [2, 4]],
    126: ["Void Spirit", "Войд Спирит", [2, 3]],
    128: ["Snapfire", "Снепфайр", [2, 4, 5]],
    129: ["Mars", "Марс", [2, 3]],
    131: ["Ringmaster", "Рингмастер", [4, 5]],
    135: ["Dawnbreaker", "Даунбрейкер", [1, 3, 4]],
    136: ["Marci", "Марси", [1, 3, 4]],
    137: ["Primal Beast", "Праймал Бист", [2, 3]],
    138: ["Muerta", "Муэрта", [1, 2, 4]],
    145: ["Kez", "Кез", [1, 2]],
}

# Алиасы: сленг и сокращения -> английское имя героя (как в OpenDota)
HERO_ALIASES = {
    "па": "Phantom Assassin", "фантомка": "Phantom Assassin", "pa": "Phantom Assassin",
    "вк": "Wraith King", "леорик": "Wraith King", "wk": "Wraith King",
    "гуля": "Lifestealer", "найкс": "Lifestealer", "ls": "Lifestealer",
    "цм": "Crystal Maiden", "цмка": "Crystal Maiden", "cm": "Crystal Maiden",
    "пудж": "Pudge", "мясо": "Pudge", "рутж": "Pudge",
    "ам": "Anti-Mage", "антимаг": "Anti-Mage", "am": "Anti-Mage",
    "баланар": "Night Stalker", "нс": "Night Stalker", "ns": "Night Stalker",
    "фурион": "Nature's Prophet", "фур": "Nature's Prophet", "np": "Nature's Prophet",
    "снайп": "Sniper",
    "шейкер": "Earthshaker", "ес": "Earthshaker", "es": "Earthshaker",
    "сф": "Shadow Fiend", "sf": "Shadow Fiend",
    "од": "Outworld Destroyer", "od": "Outworld Destroyer",
}
